config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/', include('movie.urls'))
]

movie/urls.py
from django.urls import path
from . import views 
app_name = "movie"

urlpatterns =[
    path('',views.index, name="index"),
    path('regist/', views.regist, name="regist"),
    path('<int:m_id>', views.detail, name="detail"),
    path('<int:m_id>/edit/', views.edit,name="edit"),
    path('<int:m_id>/delete/', views.delete, name="delete"),
    path('search/',views.search,name="search"),
    path('interest/', views.movie_sort,name="score"),
    path('popular/',views.movie_sort,name="audience"),
    path('genre/', views.movie_sort,name="genre"),


]

movie/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title=models.CharField(max_length=50)
    title_en = models.CharField(max_length=50)
    audience =models.IntegerField()
    open_date = models.DateTimeField()
    genre =models.CharField(max_length=50)
    watch_grade=models.CharField(max_length=50)
    score=models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()

movie/views.py
from django.shortcuts import render,redirect
from .models import Movie
import csv
from datetime import datetime
from django.urls import resolve
from django.conf import settings
import os
# Create your views here.


def index(request):
    movie = Movie.objects.all()
      
    if len(movie) == 0:
        with open(os.path.join(settings.BASE_DIR,'movie','data.csv'), 'r', encoding='utf-8-sig') as csv_file:
            # csv 파일을 Dictionary 형식으로 읽어옴.
            csv_data = csv.DictReader(csv_file, delimiter=",")
            for data in csv_data:
                movie = Movie()
                movie.title = data['title']
                movie.title_en = data['title_en']
                movie.audience = data['audience']
                # string으로 되어있는 부분을 datetime 형식으로 변환.
                movie.open_date = datetime.strptime(data['open_date'], "%Y%m%d")
                movie.genre = data['genre']
                movie.watch_grade = data['watch_grade']
                movie.score = data['score']
                movie.poster_url = data['poster_url']
                movie.description = data['description']

                movie.save()
                # print(data)
        movie = Movie.objects.all()

    context = {
        "movie": movie
    }
    return render(request, 'movie/index.html', context)


def regist(request):
    if request.method=='POST':
        
        print("ddd")
        movie = Movie()
        movie.title = request.POST.get('title')
        movie.title_en = request.POST.get('title_en')
        movie.audience = request.POST.get('audience')
        movie.score = request.POST.get('score')
        movie.open_date = request.POST.get('open_date')
        movie.genre = request.POST.get('genre')
        movie.watch_grade = request.POST.get('watch_grade')
        movie.poster_url = request.POST.get('poster_url')
        movie.description = request.POST.get('description')

        movie.save()
        print("ddd")
        return redirect("movie:index")
    else: 
        print("ddd")
        return render(request , "movie/regist.html")
        


def detail(request,m_id):
    movie=Movie.objects.get(id=m_id)
    context={
        "movie" : movie
    }
    return render(request, 'movie/detail.html',context)

def edit(request, m_id):
    movie = Movie.objects.get(id=m_id)

    if request.method == "POST":
        movie.title = request.POST.get('title')
        movie.title_en = request.POST.get('title_en')
        movie.audience = request.POST.get('audience')
        movie.score = request.POST.get('score')
        movie.open_date = request.POST.get('open_date')
        movie.genre = request.POST.get('genre')
        movie.watch_grade = request.POST.get('watch_grade')
        movie.poster_url = request.POST.get('poster_url')
        movie.description = request.POST.get('description')

        movie.save()
        return redirect('movie:detail', m_id)
    else:
        context = {
            "movie": movie 
        }
        return render(request,'movie/edit.html', context)

    

def delete(request, m_id):
    
    if request.method == "POST":
        movie = Movie.objects.get(id=m_id)
        movie.delete()
        return redirect('movie:index')
    else:
        return redirect('movie:detail', m_id)

def search(request):
    search=request.GET.get('search')
    movie=Movie.objects.filter(title__contains=search)

    context={
        "movie" : movie,
        "search" : search
    }
    return render(request,'movie/search.html',context)

def movie_sort(request):
    sorttype=resolve(request.path_info).url_name
    movies=Movie.objects.order_by(f'-{sorttype}')
    context={
        "movies":movies
    }
    return render(request,'movie/index.html',context)

movie/templates/movie/detail.html
{%extends 'base.html'%}

{%block body%}
<table class="table">
    <tr>
    <td>ID</td>
    <td>{{movie.id}}</td>
    </tr>
    <tr>
        <td>Audience</td>
        <td>{{movie.audience}}</td>
    </tr>
    <tr>
        <td>Open Date</td>
        <td>{{movie.open_date}}</td>
    </tr>
    <tr>
        <td>Genre</td>
        <td>{{movie.genre}}</td>
    </tr>
    <tr>
        <td>Watch Grade</td>
        <td>{{movie.watch_grade}}</td>
    </tr>
    <tr>
        <td>Score</td>
        <td>{{movie.score}}</td>
    </tr>
    <tr>
        <td>Poster</td>
        <td><img src="{{movie.poster_url}}" alt="POSTER" width="600" height="500"</td>
    </tr>
    <tr>
        <td>Description</td>
        <td>{{movie.description}}</td>
    </tr>
</table>
<div class="contain" align="right">
        <form action='{% url "movie:delete" movie.id %}' method='POST'>
            {% csrf_token %}
            <a class="btn btn-primary" href="{% url 'movie:index' %}" role="button">List</a>
            <a class="btn btn-primary" href="{% url 'movie:edit' movie.id %}" role="button">Edit</a>
            <a class="btn btn-outline-danger" href="#" role="button" onclick="this.parentNode.submit()">Delete</a>
        </form>
    </div>
{%endblock%}

movie/templates/movie/edit.html
  
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <form action='' method='POST'>
        {% csrf_token %}
        <table class="table">
        <tr>
            <td><label for="title">제목</label></td>
            <td><input type="text" name="title" id="title" value="{{ movie.title }}"></td>
        </tr>
        <tr>
            <td><label for="title_en">영문 제목</label></td>
            <td><input type="text" name="title_en" id="title_en" value="{{ movie.title_en }}"></td>
        </tr>    
        <tr>
            <td> 관객수</td>
            <td><input type="number" name="audience" value="{{ movie.audience }}"></td>
        </tr>
        <tr>
            <td> 개봉일</td>
            <td><input type="date" name="open_date" value="{{ movie.open_date|date:'Y-m-d' }}"></td>
        </tr>
        <tr> 
            <td> 장르</td>
            <td><input type="text" name="genre"  value="{{ movie.genre }}"></td>
        </tr>
        <tr>
            <td> 등급</td>
            <td><input type="text" name="watch_grade"  value="{{ movie.watch_grade }}"></td>
        </tr>
        <tr>
            <td> 평점</td>
            <td><input type="number" name="score" step=0.01  value="{{ movie.score }}"></td>
        </tr>
        <tr>
            <td> 포스터 URL</td>
            <td><textarea name="poster_url" cols="30" rows="5">{{ movie.poster_url }}</textarea></td>
        </tr>
        <tr>
            <td> 설명</td>
            <td><textarea name="description" cols="30" rows="10">{{ movie.description }}</textarea></td>
        </tr>
        </table>
        <div class="contain" align="right">
            <input class="btn btn-outline-success btn-lg" type='submit' value="수정">
            <a class="btn btn-outline-warning btn-lg" href="{% url 'movie:detail' movie.id %}" role="button">취소</a>
        </div>
    </form>
</div>
{% endblock %}

movie/templates/movie/index.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<h1>Movie List</h1>
<ul>
</div>

<table class="table">
        <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Genre</th>
                <th>Score</th>
                <th>Audience</th>
        </tr>
        {% for mov in movie %}
        <tr>
            <th>{{mov.id}}</th>
            <th><a href="{% url 'movie:detail' mov.id %}">{{mov.title}} <br> ({{mov.title_en}})</a></th>
            <th>{{mov.genre}}</th>
            <th>{{mov.score}}</th>
            <th>{{mov.audience}}</th>
        </tr>             
        {%empty%}
        <div class="container">
                <h4>no list</h4>
        </div>
        {% endfor %}
        </table>

        <div class="container" align="center">
                <a class="btn btn-primary btn-sm btn-block" href="{% url 'movie:regist' %}" role="button">Add movie</a>
        </div>

{% endblock %}

movie/templates/movie/regist.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <form action='' method='POST'>
        {% csrf_token %}
        <table class="table">
                <tr>
                    <td><label for="title">제목</label></td>
                    <td><input type="text" name="title" id="title" required></td>
                </tr>
                <tr>
                    <td><label for="title_en">영문 제목</label></td>
                    <td><input type="text" name="title_en" id="title_en" required></td>
                </tr>    
                <tr>
                    <td> 관객수</td>
                    <td><input type="number" name="audience"></td>
                </tr>
                <tr>
                    <td> 개봉일</td>
                    <td><input type="date" name="open_date" required></td>
                </tr>
                <tr> 
                    <td> 장르</td>
                    <td><input type="text" name="genre" required></td>
                </tr>
                <tr>
                    <td> 등급</td>
                    <td><input type="text" name="watch_grade" required></td>
                </tr>
                <tr>
                    <td> 평점</td>
                    <td><input type="number" name="score" step=0.01  ></td>
                </tr>
                <tr>
                    <td> 포스터 URL</td>
                    <td><input type="url" name="poster_url" style="width:233px"></td>
                </tr>
                <tr>
                    <td> 설명</td>
                    <td><textarea name="description" cols="30" rows="10"></textarea></td>
                </tr>
            </table>
            <div class="container" align="center">
                <input class="btn btn-lg btn-primary" type='submit' value="등록">
            </div>
    </form>
</div>
{% endblock %}

movie/templates/movie/search.html
{% extends 'base.html' %}
{% block body %}
<h2 class="container">Search : {{ search }}</h2>
<table class="table">
    <tr>
        <th>ID</th>
        <th>TITLE</th>
        <th>GENRE</th>
        <th>SCORE</th>
    </tr>
    {% for movie in movies %}
    <tr>
        <th>{{ movie.id }}</th>
        <th><a href="{% url 'movie:detail' movie.id %}">{{ movie.title }} <br>({{ movie.title_en }})</a></th>
        <th>{{ movie.genre }}</th>
        <th>{{ movie.score }}</th>
    </tr>
    {% empty %}
    <div class="container">
        <h3>No Movie!</h3>
    </div>
    {% endfor %}
</table>
{% endblock %}